"""add event_logs table

Revision ID: bdc939085501
Revises: 8603d86f999e
Create Date: 2026-07-23 23:50:16.324782

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "bdc939085501"
down_revision: str | Sequence[str] | None = "8603d86f999e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "event_logs",
        sa.Column(
            "event_type",
            sa.Enum("DOMAIN_CREATED", "DOMAIN_DELETED", name="event_type"),
            nullable=False,
        ),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("event_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_event_logs_user_id"), "event_logs", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_event_logs_user_id"), table_name="event_logs")
    op.drop_table("event_logs")
    # ### end Alembic commands ###

    # drop_table() does not drop the native Postgres enum type it created —
    # left alone, re-running upgrade() after a downgrade fails with
    # "type ... already exists".
    sa.Enum(name="event_type").drop(op.get_bind(), checkfirst=True)
